{{- if and (.Values.expose.enabled) (eq .Values.expose.environment "gardener") -}}
{{- $name := default "approuter-chart" .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- $fullName := include "k8s-e2e-app-helm.fullname" . -}}
{{- $svcName := index .Values "approuter-chart" "name" | default (printf "%s-%s-svc" .Release.Name $name) | trunc 63 | trimSuffix "-" | quote -}}
{{- $svcPort := dig "approuter-chart" "service" "port" 8080 (.Values | merge (dict)) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/session-cookie-name: "JSESSIONID"
    {{- if eq .Values.expose.environment "gardener" }}
    cert.gardener.cloud/purpose: "managed"
    {{- else }}
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: {{ .Values.expose.ingress.issuer.name | default "letsencrypt-production" | quote }}
    {{ end }}
spec:
  tls:
    - hosts:
      {{- if .Values.expose.ingress.shortRoute }}
      - {{.Values.expose.ingress.shortRoute | quote }}
      {{ end -}}
      - {{ .Values.expose.ingress.exposedRoute | quote }}
      {{- if .Values.expose.ingress.connectivityProxyRoute }}
      - {{ .Values.expose.ingress.connectivityProxyRoute | quote }}
      {{ end -}}
      secretName: {{ .Values.expose.ingress.secretName | default "tls-secret" | quote }}
  rules:
  - host: {{ .Values.expose.ingress.exposedRoute | quote }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ $svcName }}
              port:
                number: {{ $svcPort }}

{{- end }}
